name: ci-partial

on:
  workflow_dispatch:

jobs:
  build-projects:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [yahooanswers-grab]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build ${{ matrix.project }}
        working-directory: ${{ matrix.project }}
        run: ./build.sh
