name: ci

on:
  push:
    branches:
      - main
    paths-ignore:
      # Do not trigger on changes that are likely not code changes, such as README
      - '**.md'
      # Do not trigger on workflow changes, can do manual trigger if needed
      - '.github/**'
  schedule:
    - cron:  '*/30 * * * *'
  workflow_dispatch:
    inputs:
      invoke_args:
        description: 'Invoke arguments'
        required: true
        default: 'buildall --force'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Set up build requirements
        run: pip install -r requirements.txt
      -
        name: Build projects from manual trigger
        if: ${{ github.event_name }} == "workflow_dispatch"
        run: |
          invoke -e ${{ github.event.inputs.invok_args }}

        name: Build projects
        if: ${{ github.event_name }} != "workflow_dispatch"
        run: |
          invoke -e buildall
