name: scripts

on: 
  push:
    paths:
      - '**.sh'
      - '**.py'

jobs:
  shell-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run shellcheck on scripts
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update && apt-get install -qy shellcheck
          find . -name "*.sh" | xargs -I{} sh -c "echo Checking {}; shellcheck {}"

  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install --upgrade black flake8
      - name: Run black check
        run: black -c -l 79 *.py
      - name: Run flake8 test
        run: flake8 --ignore=E501 *.py
